name: API Testing

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Test and Scan the APIs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up environment
        run: |
          echo "TARGETS=https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/secrets https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/preferences https://another-target-url.com/api" >> $GITHUB_ENV

      - name: Run ZAP Scans and Collect Reports
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports
          for target in $TARGETS; do
            docker run -v $(pwd)/zap_reports:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable /bin/sh -c "zap-api-scan.py -t $target -f openapi -J /zap/wrk/zap_reports/report_$(echo $target | md5sum | cut -d' ' -f1).json || true"
          done

      - name: Merge JSON Reports
        run: |
          echo '[
          $(for file in zap_reports/*.json; do cat $file; echo ','; done | sed '$ s/,$//')
          ]' > zap_reports/merged_report.json

      - name: Install zap-cli
        run: |
          pip install zap-cli

      - name: Generate HTML Reports
        run: |
          mkdir -p zap_html_reports
          chmod 777 zap_html_reports
          for report in zap_reports/*.json; do
            zap-cli --zap-url http://localhost:8080 --zap-apikey '' report -f json -o $report -F html > zap_html_reports/$(basename ${report%.json}).html || true
          done

      - name: Upload ZAP HTML Reports
        uses: actions/upload-artifact@v2
        with:
          name: zap-html-reports
          path: zap_html_reports




      - name: Generate Consolidated Report
        run: |
          docker run -v $(pwd)/zap_reports:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable /bin/sh -c "zap-api-scan.py -J /zap/wrk/zap_reports/final_report.json -w /zap/wrk/zap_reports/final_report.md -r /zap/wrk/zap_reports/final_report.html -I /zap/wrk/zap_reports/merged_report.json || true"

      - name: List zap_reports directory
        run: ls -al zap_reports

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report-html
          path: zap_reports/final_report.html
          if-no-files-found: warn
