name: API Testing

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/secrets'
          - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/payments/summary/get'
          - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/accounts/get'
    name: Scan the web application at ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Report Directory
        run: mkdir -p zap_reports

      - name: Sanitize URL and Set Filename
        id: sanitize
        run: echo "report_name=$(echo ${{ matrix.target }} | sed 's/[^a-zA-Z0-9]/_/g').html" >> $GITHUB_ENV

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: ${{ matrix.target }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -r /zap/wrk/zap_reports/${{ env.report_name }}'

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-Reports-${{ matrix.target | slug }}
          path: zap_reports/*.html

  send_reports:
    runs-on: ubuntu-latest
    needs: zap_scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Reports
        uses: actions/download-artifact@v2
        with:
          name: ZAP-Reports
          path: zap_reports

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Email Dependencies
        run: pip install secure-smtplib

      - name: Send Email with Reports
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python Utilities/send_email_script.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL zap_reports/*.html
