name: API Testing

on:
  push:
    branches:
      - main

jobs:
    zap_scan:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target:
              - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/secrets'
              - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/payments/summary/get'
              - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/accounts/get'
      name: Scan the web application at ${{ matrix.target }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: master

        - name: ZAP Scan
          uses: zaproxy/action-api-scan@v0.7.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            format: openapi
            target: ${{ matrix.target }}
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'


        - name: pwd
          run: pwd

        - name: ls
          run: ls


#        - name: Upload ZAP Report
#          uses: actions/upload-artifact@v2
#          with:
#            name: ZAP-Report-${{ matrix.target }}
#            path: 'path_to_zap_report_directory/*'