name: API Testing

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Test and Scan the APIs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up environment
        run: |
          echo "TARGETS=https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/secrets https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/preferences https://another-target-url.com/api" >> $GITHUB_ENV

      - name: Run ZAP Scans and Collect Reports
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports
          for target in $TARGETS; do
            docker run -v $(pwd)/zap_reports:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable /bin/sh -c "zap-api-scan.py -t $target -f openapi -J /zap/wrk/report_$(echo $target | md5sum | cut -d' ' -f1).json -r /zap/wrk/report_$(echo $target | md5sum | cut -d' ' -f1).html || true"
          done

      - name: Merge JSON Reports
        run: |
          echo '[' > zap_reports/temp_merged_report.json
          for file in zap_reports/*.json; do
            cat $file >> zap_reports/temp_merged_report.json
            echo ',' >> zap_reports/temp_merged_report.json
          done
          sed -i '$ s/,$//' zap_reports/temp_merged_report.json
          echo ']' >> zap_reports/temp_merged_report.json
          mv zap_reports/temp_merged_report.json zap_reports/merged_report.json

      - name: Show Merged Report
        run: |
          cat zap_reports/merged_report.json

      - name: Generate Consolidated Report
        run: |
          docker run -v $(pwd)/zap_reports:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable /bin/sh -c "zap-api-scan.py -J /zap/wrk/final_report.json -w /zap/wrk/final_report.md -r /zap/wrk/final_report.html -I /zap/wrk/merged_report.json || true"

      - name: Show ZAP Docker Logs
        run: |
          docker logs $(docker ps -lq)

      - name: List zap_reports directory
        run: |
          ls -al zap_reports

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report-html
          path: zap_reports/final_report.html
          if-no-files-found: warn
