name: API Testing

on:
  push:
    branches:
      - main
#test
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/secrets'
          - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/payments/summary/get'
          - 'https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/accounts/get'
    name: Scan the web application at ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Report Directory
        run: mkdir -p zap_reports

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: ${{ matrix.target }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -r zap_reports/report_${{ matrix.target | slug }}.html'

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: ZAP-Reports-${{ matrix.target | slug }}
          path: zap_reports/report_${{ matrix.target | slug }}.html

  merge_reports:
    runs-on: ubuntu-latest
    needs: zap_scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Reports
        uses: actions/download-artifact@v2
        with:
          name: ZAP-Reports
          path: zap_reports

      - name: Merge Reports
        run: |
          echo "<html><body>" > merged-report.html
          for report in zap_reports/*.html; do
            echo "<h2>Report: $report</h2>" >> merged-report.html
            cat "$report" >> merged-report.html
          done
          echo "</body></html>" >> merged-report.html

      - name: Upload Merged Report
        uses: actions/upload-artifact@v2
        with:
          name: Merged-ZAP-Report
          path: merged-report.html

  send_reports:
    runs-on: ubuntu-latest
    needs: [zap_scan, merge_reports]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Reports
        uses: actions/download-artifact@v2
        with:
          name: ZAP-Reports
          path: zap_reports

      - name: Download Merged Report
        uses: actions/download-artifact@v2
        with:
          name: Merged-ZAP-Report
          path: merged-report.html

      - name: Send Email with Reports
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python Utilities/send_email_script.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL zap_reports/*.html merged-report.html
