name: API Testing

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Test and Scan the APIs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test directory
        run: pwd

      - name: List files
        run: ls

      - name: Set up environment
        run: |
          echo "TARGETS=https://bscytxzsc3.execute-api.ap-south-1.amazonaws.com/user/secrets https://another-target-url.com/api" >> $GITHUB_ENV

      - name: Run ZAP Scans and Collect Reports
        run: |
          mkdir -p zap_reports
          for target in $TARGETS; do
            docker run -v $(pwd)/zap_reports:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py -t $target -f openapi -J zap_reports/report_$(echo $target | md5sum | cut -d' ' -f1).json
          done

      - name: Merge JSON Reports
        run: |
          echo '[
          $(for file in zap_reports/*.json; do cat $file; echo ','; done | sed '$ s/,$//')
          ]' > zap_reports/merged_report.json

      - name: Generate Consolidated Report
        run: |
          docker run -v $(pwd)/zap_reports:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py -J zap_reports/final_report.json -w zap_reports/final_report.md -r zap_reports/final_report.html -I zap_reports/merged_report.json

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report-html
          path: zap_reports/final_report.html
